apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus-prometheus
    app: prometheus
    release: prometheus
    role: alert-rules
  name: kafka-alerts
  namespace: monitoring
spec:
  groups:
  - name: kafka.rules
    rules:
    - alert: BrokerOverLoaded
      expr: avg(sum by(brokerId, kafka_cr, namespace) (rate(kafka_network_requestmetrics_requests_total[5m]))) by (kafka_cr, namespace) > 20
      for: 2m
      labels:
        severity: alert
        alertGroup: kafka
      annotations:
        description: 'broker {{ $labels.brokerId }} overloaded (current value is: {{ $value }})'
        summary: 'broker overloaded'
        # If brokerConfigGroup is defined it will override scaled broker config
        # brokerConfigGroup: 'default_group'
        storageClass: 'default'
        mountPath: '/kafkalog'
        diskSize: '20G'
        image: 'banzaicloud/kafka:2.13-2.4.0'
        command: 'upScale'
    - alert: PartitionCountHigh
      expr: max(kafka_server_replicamanager_partitioncount)  by (namespace, kafka_cr) > 100
      for: 2m
      labels:
        severity: alert
        alertGroup: kafka
      annotations:
        description: 'broker {{ $labels.brokerId }} has high partition count'
        summary: 'high partition count'
        storageClass: 'default'
        mountPath: '/kafkalog'
        diskSize: '20G'
        image: 'banzaicloud/kafka:2.13-2.4.0'
        command: 'upScale'